from __future__ import annotations
from typing import Any
TOPICS={"P01-G01":"authority_phase0_intake","P01-G02":"source_provenance_license","P01-G03":"schema_canonical_object","P01-G04":"metadata_completeness","P01-G05":"label_mapping","P01-G06":"preprocessing_fit_scope","P01-G07":"split_disjointness","P01-G08":"leakage_chronology","P01-G09":"low_calibration_budgets","P01-G10":"window_identity","P01-G11":"quality_coverage","P01-G12":"matched_keys_ablation_readiness","P01-G13":"cards_limitations","P01-G14":"manifest_path_hash_closure","P01-G15":"phase2_compatibility","P01-G16":"complete_artifact_closure"}
OWNERS={"P01-G01":"GOVERNANCE_AND_PHASE0","P01-G02":"METHOD_SELECTION_AND_OWNER","P01-G03":"REGISTRY","P01-G04":"L1_METADATA","P01-G05":"L1_LABELS","P01-G06":"PROTOCOL_AND_L1_PREPROCESSING","P01-G07":"PROTOCOL_AND_L1_SPLITS","P01-G08":"PROTOCOL_AND_L1_LEAKAGE","P01-G09":"PROTOCOL_AND_L1_BUDGETS","P01-G10":"L1_WINDOWS","P01-G11":"L1_QUALITY","P01-G12":"PROTOCOL_AND_L1_READINESS","P01-G13":"L0_BOUNDARY_AND_L1_CARDS","P01-G14":"BUILD_BOOK_AND_L1_MANIFESTS","P01-G15":"BUILD_BOOK_AND_P02_CONSUMER","P01-G16":"EXECUTION_PLAN_AND_L1_BUNDLE"}
EVIDENCE={
"P01-G01":["manifests/phase_01/test_manifest.json","authority_manifest.json"],"P01-G02":["reports/phase_01/sources/source_version_license_report.json","inputs/source_inventory.json"],"P01-G03":["reports/phase_01/validation/","records/"],"P01-G04":["reports/phase_01/metadata/metadata_completeness.json"],"P01-G05":["reports/phase_01/labels/label_map_validation.json","records/labels/"],"P01-G06":["reports/phase_01/preprocessing/fit_scope.json","records/preprocessing/"],"P01-G07":["reports/phase_01/splits/disjointness.json","records/splits/"],"P01-G08":["reports/phase_01/leakage/leakage_contamination.json"],"P01-G09":["reports/phase_01/splits/low_calibration_budgets.csv"],"P01-G10":["reports/phase_01/windows/window_timing_overlap.json","records/windows/"],"P01-G11":["reports/phase_01/quality/quality_coverage.json","records/quality/"],"P01-G12":["manifests/phase_01/layer1_ablation_readiness_l1_v1.json","reports/phase_01/readiness/matched_key_completeness.csv"],"P01-G13":["docs/cards/datasets/","docs/cards/protocols/"],"P01-G14":["manifests/phase_01/execution_bundle_manifest.json","checksums.sha256"],"P01-G15":["phase2_handoff/phase_01_to_phase_02.yaml"],"P01-G16":["manifests/phase_01/layer1_manifest.json","phase_execution_handoff.yaml"]}
FAILURE_CODES={gid:[f"{gid.replace('-','_')}_REQUIREMENT_UNSATISFIED"] for gid in TOPICS}

def evaluate(context:dict[str,Any])->list[dict[str,Any]]:
    rows=[]
    for gid,topic in TOPICS.items():
        value=context.get(topic); status="PASS" if value is True else "BLOCKED" if value is None else "FAIL"
        rows.append({"gate_id":gid,"official_or_local_name":topic,"status":status,"inputs":context.get(topic+"_inputs",[]),"procedure_version":"P01-L1-GATE-R6","observations":context.get(topic+"_observations",{}),"failure_codes":[] if status=="PASS" else context.get(topic+"_failure_codes",FAILURE_CODES[gid]),"repair_owner":OWNERS[gid],"affected_artifacts":context.get(topic+"_affected_artifacts",[]),"evidence_paths":context.get(topic+"_evidence_paths",EVIDENCE[gid]),"manifest_entry":f"manifests/phase_01/gates/{gid}.json","blocking_effect":status!="PASS"})
    return rows
